# .pre-commit-config-extra.yaml
default_stages: [pre-commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        args: [ --branch, main ]
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 2.2.239 # checkov-action v12.2017.0 == checkov 2.2.239 - keep pre-commit and github action in sync
    hooks:
      - id: checkov
        verbose: false
        args: [--download-external-modules, "true", --quiet, --compact]
  # Python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.6
    hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--settings-path=pyproject.toml", "--filter-files"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
  # - repo: local
  #   hooks:
  #     - id: pytest-check
  #       name: pytest-check
  #       entry: "uv tool run pytest"
  #       language: system
  #       pass_filenames: false
  #       always_run: true
